### ISSUE TITLE
Unable to list functions using Mistral 7B

### ISSUE THREAD

**Issue by abhinavkulkarni** [definitive-io/openassistants#104]
Hi,

Thanks for this great effort!

I was trying to run the demo using a local Mistral 7B LLM, but ran into an error.

Firstly, I ran an OpenAI compatible server using `llama.cpp` server ([link](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md)):

```
./server -m models/mistral-7b-instruct-v0.2.Q4_0.gguf -c 8192 --port 8080 --host 0.0.0.0
```

Secondly, I ran the `openassistants` backend as follows:

```
export OPENAI_API_KEY=dummy
export OPENAI_BASE_URL=http://localhost:8080/v1
./run.sh 
```

And ran the frontend as follows:

```
yarn dev
```

When I select "_What can I ask?_" option, I get the following error on the backend:

Looking at the various variables at [packages/openassistants/openassistants/llm_function_calling/selection.py:68](https://github.com/definitive-io/openassistants/tree/main/packages/openassistants/openassistants/llm_function_calling/selection.py#L68)

`subsets` is
```
[[PythonEvalFunction(id='send_purchase_inquiry_email', type='PythonEvalFunction', display_name='Send purchase inquiry email', description='Send an inquiry email about a recent purchase to an employee\n', sample_questions=['send purchase inquiry email'], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'to': {'type': 'string', 'format': 'email', 'description': 'email address to send to'}}, 'required': ['to']}), is_fallback=False, python_code='async def main(args: dict):\n  import asyncio\n  yield [{"type": "text", "text": "Sending email..."}]\n  await asyncio.sleep(2)\n  yield [{"type": "text", "text": f"Inquiry email about recent purchase sent to: {args.get(\'to\')}"}]\n'), DuckDBQueryFunction(id='show_recent_purchases', type='DuckDBQueryFunction', display_name='Show recent purchases', description='Show a list of recent purchases (last 5)\n', sample_questions=['show recent purchases'], confirm=False, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {}, 'required': []}), is_fallback=False, sqls=['SELECT purchases.id, purchases.product, employees.email\nFROM "purchases.csv"\nINNER JOIN "employees.csv" ON purchases.employee = employees.id\nORDER BY purchases.id DESC\nLIMIT 5\n'], visualizations=[], summarization='Describe these purchases', data_table_output=True, suggested_follow_ups=[], dataset='dummy-data/'), DuckDBQueryFunction(id='spend_all_product', type='DuckDBQueryFunction', display_name='Spend all products', description='Show the spend for all products (top 5)\n', sample_questions=['show spend for all products'], confirm=False, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {}, 'required': []}), is_fallback=False, sqls=['SELECT purchases.product, SUM(purchases.amount) as amount,\nFROM "purchases.csv"\nGROUP BY purchases.product\nORDER BY amount DESC\nLIMIT 5\n'], visualizations=["def create_chart_config(dataframes):\n  df = dataframes[0]\n  data = [{'x': df.iloc[:, 0].tolist(), 'y': df.iloc[:, 1].tolist(), 'type': 'bar'}]\n  layout = {'title': 'Spend per Product', 'xaxis': {'title': 'Product'}, 'yaxis': {'title': 'Total Spend'}}\n  result = {'data': data, 'layout': layout}\n\n  return result\n"], summarization='Describe the spend per product', data_table_output=True, suggested_follow_ups=[], dataset='dummy-data/'), DuckDuckGoToolFunction(id='search_web_about_hooli', type='DuckDuckGoToolFunction', display_name='Search the web using DuckDuckGo', description='Get information from DuckDuckGo\n', sample_questions=['Search the web for "pied piper"'], confirm=False, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'search query to send to DuckDuckGo'}}, 'required': ['query']}), is_fallback=False)], [PythonCallableFunction(id='find_email', type='PythonCallableFunction', display_name='Find Email', description='Find an email address', sample_questions=['Find the email address for {employee}', "What is {employee}'s email address?"], confirm=False, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'The name of the person to find the email address for'}}, 'required': ['name']}), is_fallback=False, execute_callable=<function _execute at 0x104d67ce0>, get_entity_configs_callable=<function _get_entity_configs at 0x138625940>), PythonCallableFunction(id='updatePet', type='PythonCallableFunction', display_name='updatePet', description='Update an existing pet by Id', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'data': {'anyOf': [{'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'name': {'type': 'string', 'example': 'doggie'}, 'category': {'ref': '#/components/schemas/Category'}, 'photoUrls': {'items': {'type': 'string', 'xml': {'name': 'photoUrl', 'attribute': False, 'wrapped': False}}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'tags': {'items': {'ref': '#/components/schemas/Tag'}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'pet status in the store'}}, 'type': 'object', 'required': ['name', 'photoUrls'], 'xml': {'name': 'pet', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'name': {'type': 'string', 'example': 'doggie'}, 'category': {'ref': '#/components/schemas/Category'}, 'photoUrls': {'items': {'type': 'string', 'xml': {'name': 'photoUrl', 'attribute': False, 'wrapped': False}}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'tags': {'items': {'ref': '#/components/schemas/Tag'}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'pet status in the store'}}, 'type': 'object', 'required': ['name', 'photoUrls'], 'xml': {'name': 'pet', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'name': {'type': 'string', 'example': 'doggie'}, 'category': {'ref': '#/components/schemas/Category'}, 'photoUrls': {'items': {'type': 'string', 'xml': {'name': 'photoUrl', 'attribute': False, 'wrapped': False}}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'tags': {'items': {'ref': '#/components/schemas/Tag'}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'pet status in the store'}}, 'type': 'object', 'required': ['name', 'photoUrls'], 'xml': {'name': 'pet', 'attribute': False, 'wrapped': False}}]}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386277e0>, get_entity_configs_callable=None), PythonCallableFunction(id='addPet', type='PythonCallableFunction', display_name='addPet', description='Add a new pet to the store', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'data': {'anyOf': [{'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'name': {'type': 'string', 'example': 'doggie'}, 'category': {'ref': '#/components/schemas/Category'}, 'photoUrls': {'items': {'type': 'string', 'xml': {'name': 'photoUrl', 'attribute': False, 'wrapped': False}}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'tags': {'items': {'ref': '#/components/schemas/Tag'}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'pet status in the store'}}, 'type': 'object', 'required': ['name', 'photoUrls'], 'xml': {'name': 'pet', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'name': {'type': 'string', 'example': 'doggie'}, 'category': {'ref': '#/components/schemas/Category'}, 'photoUrls': {'items': {'type': 'string', 'xml': {'name': 'photoUrl', 'attribute': False, 'wrapped': False}}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'tags': {'items': {'ref': '#/components/schemas/Tag'}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'pet status in the store'}}, 'type': 'object', 'required': ['name', 'photoUrls'], 'xml': {'name': 'pet', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'name': {'type': 'string', 'example': 'doggie'}, 'category': {'ref': '#/components/schemas/Category'}, 'photoUrls': {'items': {'type': 'string', 'xml': {'name': 'photoUrl', 'attribute': False, 'wrapped': False}}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'tags': {'items': {'ref': '#/components/schemas/Tag'}, 'type': 'array', 'xml': {'attribute': False, 'wrapped': True}}, 'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'pet status in the store'}}, 'type': 'object', 'required': ['name', 'photoUrls'], 'xml': {'name': 'pet', 'attribute': False, 'wrapped': False}}]}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c8220>, get_entity_configs_callable=None), PythonCallableFunction(id='findPetsByStatus', type='PythonCallableFunction', display_name='findPetsByStatus', description='Multiple status values can be provided with comma separated strings', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'params': {'type': 'object', 'properties': {'status': {'type': 'string', 'enum': ['available', 'pending', 'sold'], 'description': 'Status values that need to be considered for filter', 'default': 'available'}}, 'required': []}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c8900>, get_entity_configs_callable=None)], [PythonCallableFunction(id='findPetsByTags', type='PythonCallableFunction', display_name='findPetsByTags', description='Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'params': {'type': 'object', 'properties': {'tags': {'items': {'type': 'string'}, 'type': 'array', 'description': 'Tags to filter by'}}, 'required': []}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x138627f60>, get_entity_configs_callable=None), PythonCallableFunction(id='getPetById', type='PythonCallableFunction', display_name='getPetById', description='Returns a single pet', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'path_params': {'type': 'object', 'properties': {'petId': {'type': 'integer', 'schema_format': 'int64', 'description': 'ID of pet to return'}}, 'required': ['petId']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c8ea0>, get_entity_configs_callable=None), PythonCallableFunction(id='updatePetWithForm', type='PythonCallableFunction', display_name='updatePetWithForm', description='Updates a pet in the store with form data', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'params': {'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Name of pet that needs to be updated'}, 'status': {'type': 'string', 'description': 'Status of pet that needs to be updated'}}, 'required': []}, 'path_params': {'type': 'object', 'properties': {'petId': {'type': 'integer', 'schema_format': 'int64', 'description': 'ID of pet that needs to be updated'}}, 'required': ['petId']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c8680>, get_entity_configs_callable=None), PythonCallableFunction(id='deletePet', type='PythonCallableFunction', display_name='deletePet', description='Deletes a pet', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'headers': {'type': 'object', 'properties': {'api_key': {'type': 'string'}}, 'required': []}, 'path_params': {'type': 'object', 'properties': {'petId': {'type': 'integer', 'schema_format': 'int64', 'description': 'Pet id to delete'}}, 'required': ['petId']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c9080>, get_entity_configs_callable=None)], [PythonCallableFunction(id='uploadFile', type='PythonCallableFunction', display_name='uploadFile', description='uploads an image', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'params': {'type': 'object', 'properties': {'additionalMetadata': {'type': 'string', 'description': 'Additional Metadata'}}, 'required': []}, 'path_params': {'type': 'object', 'properties': {'petId': {'type': 'integer', 'schema_format': 'int64', 'description': 'ID of pet to update'}}, 'required': ['petId']}, 'data': {'type': 'string', 'schema_format': 'binary'}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c9760>, get_entity_configs_callable=None), PythonCallableFunction(id='getInventory', type='PythonCallableFunction', display_name='getInventory', description='Returns a map of status codes to quantities', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386c9e40>, get_entity_configs_callable=None), PythonCallableFunction(id='placeOrder', type='PythonCallableFunction', display_name='placeOrder', description='Place a new order in the store', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'data': {'anyOf': [{'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'petId': {'type': 'integer', 'schema_format': 'int64', 'example': 198772}, 'quantity': {'type': 'integer', 'schema_format': 'int32', 'example': 7}, 'shipDate': {'type': 'string', 'schema_format': 'date-time'}, 'status': {'type': 'string', 'enum': ['placed', 'approved', 'delivered'], 'description': 'Order Status', 'example': 'approved'}, 'complete': {'type': 'boolean'}}, 'type': 'object', 'xml': {'name': 'order', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'petId': {'type': 'integer', 'schema_format': 'int64', 'example': 198772}, 'quantity': {'type': 'integer', 'schema_format': 'int32', 'example': 7}, 'shipDate': {'type': 'string', 'schema_format': 'date-time'}, 'status': {'type': 'string', 'enum': ['placed', 'approved', 'delivered'], 'description': 'Order Status', 'example': 'approved'}, 'complete': {'type': 'boolean'}}, 'type': 'object', 'xml': {'name': 'order', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'petId': {'type': 'integer', 'schema_format': 'int64', 'example': 198772}, 'quantity': {'type': 'integer', 'schema_format': 'int32', 'example': 7}, 'shipDate': {'type': 'string', 'schema_format': 'date-time'}, 'status': {'type': 'string', 'enum': ['placed', 'approved', 'delivered'], 'description': 'Order Status', 'example': 'approved'}, 'complete': {'type': 'boolean'}}, 'type': 'object', 'xml': {'name': 'order', 'attribute': False, 'wrapped': False}}]}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386ca520>, get_entity_configs_callable=None), PythonCallableFunction(id='getOrderById', type='PythonCallableFunction', display_name='getOrderById', description='For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'path_params': {'type': 'object', 'properties': {'orderId': {'type': 'integer', 'schema_format': 'int64', 'description': 'ID of order that needs to be fetched'}}, 'required': ['orderId']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386cac00>, get_entity_configs_callable=None)], [PythonCallableFunction(id='deleteOrder', type='PythonCallableFunction', display_name='deleteOrder', description='For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'path_params': {'type': 'object', 'properties': {'orderId': {'type': 'integer', 'schema_format': 'int64', 'description': 'ID of the order that needs to be deleted'}}, 'required': ['orderId']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386caca0>, get_entity_configs_callable=None), PythonCallableFunction(id='createUser', type='PythonCallableFunction', display_name='createUser', description='This can only be done by the logged in user.', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'data': {'anyOf': [{'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'username': {'type': 'string', 'example': 'theUser'}, 'firstName': {'type': 'string', 'example': 'John'}, 'lastName': {'type': 'string', 'example': 'James'}, 'email': {'type': 'string', 'example': 'john@email.com'}, 'password': {'type': 'string', 'example': '12345'}, 'phone': {'type': 'string', 'example': '12345'}, 'userStatus': {'type': 'integer', 'schema_format': 'int32', 'description': 'User Status', 'example': 1}}, 'type': 'object', 'xml': {'name': 'user', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'username': {'type': 'string', 'example': 'theUser'}, 'firstName': {'type': 'string', 'example': 'John'}, 'lastName': {'type': 'string', 'example': 'James'}, 'email': {'type': 'string', 'example': 'john@email.com'}, 'password': {'type': 'string', 'example': '12345'}, 'phone': {'type': 'string', 'example': '12345'}, 'userStatus': {'type': 'integer', 'schema_format': 'int32', 'description': 'User Status', 'example': 1}}, 'type': 'object', 'xml': {'name': 'user', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'username': {'type': 'string', 'example': 'theUser'}, 'firstName': {'type': 'string', 'example': 'John'}, 'lastName': {'type': 'string', 'example': 'James'}, 'email': {'type': 'string', 'example': 'john@email.com'}, 'password': {'type': 'string', 'example': '12345'}, 'phone': {'type': 'string', 'example': '12345'}, 'userStatus': {'type': 'integer', 'schema_format': 'int32', 'description': 'User Status', 'example': 1}}, 'type': 'object', 'xml': {'name': 'user', 'attribute': False, 'wrapped': False}}]}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386cb380>, get_entity_configs_callable=None), PythonCallableFunction(id='createUsersWithListInput', type='PythonCallableFunction', display_name='createUsersWithListInput', description='Creates list of users with given input array', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'json': {'items': {'ref': '#/components/schemas/User'}, 'type': 'array'}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386dc0e0>, get_entity_configs_callable=None)], [PythonCallableFunction(id='loginUser', type='PythonCallableFunction', display_name='loginUser', description='Logs user into the system', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'params': {'type': 'object', 'properties': {'username': {'type': 'string', 'description': 'The user name for login'}, 'password': {'type': 'string', 'description': 'The password for login in clear text'}}, 'required': []}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386cbf60>, get_entity_configs_callable=None), PythonCallableFunction(id='logoutUser', type='PythonCallableFunction', display_name='logoutUser', description='Logs out current logged in user session', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386cb7e0>, get_entity_configs_callable=None), PythonCallableFunction(id='getUserByName', type='PythonCallableFunction', display_name='getUserByName', description='Get user by user name', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'path_params': {'type': 'object', 'properties': {'username': {'type': 'string', 'description': 'The name that needs to be fetched. Use user1 for testing. '}}, 'required': ['username']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386caf20>, get_entity_configs_callable=None)], [PythonCallableFunction(id='updateUser', type='PythonCallableFunction', display_name='updateUser', description='This can only be done by the logged in user.', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'path_params': {'type': 'object', 'properties': {'username': {'type': 'string', 'description': 'name that need to be deleted'}}, 'required': ['username']}, 'data': {'anyOf': [{'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'username': {'type': 'string', 'example': 'theUser'}, 'firstName': {'type': 'string', 'example': 'John'}, 'lastName': {'type': 'string', 'example': 'James'}, 'email': {'type': 'string', 'example': 'john@email.com'}, 'password': {'type': 'string', 'example': '12345'}, 'phone': {'type': 'string', 'example': '12345'}, 'userStatus': {'type': 'integer', 'schema_format': 'int32', 'description': 'User Status', 'example': 1}}, 'type': 'object', 'xml': {'name': 'user', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'username': {'type': 'string', 'example': 'theUser'}, 'firstName': {'type': 'string', 'example': 'John'}, 'lastName': {'type': 'string', 'example': 'James'}, 'email': {'type': 'string', 'example': 'john@email.com'}, 'password': {'type': 'string', 'example': '12345'}, 'phone': {'type': 'string', 'example': '12345'}, 'userStatus': {'type': 'integer', 'schema_format': 'int32', 'description': 'User Status', 'example': 1}}, 'type': 'object', 'xml': {'name': 'user', 'attribute': False, 'wrapped': False}}, {'properties': {'id': {'type': 'integer', 'schema_format': 'int64', 'example': 10}, 'username': {'type': 'string', 'example': 'theUser'}, 'firstName': {'type': 'string', 'example': 'John'}, 'lastName': {'type': 'string', 'example': 'James'}, 'email': {'type': 'string', 'example': 'john@email.com'}, 'password': {'type': 'string', 'example': '12345'}, 'phone': {'type': 'string', 'example': '12345'}, 'userStatus': {'type': 'integer', 'schema_format': 'int32', 'description': 'User Status', 'example': 1}}, 'type': 'object', 'xml': {'name': 'user', 'attribute': False, 'wrapped': False}}]}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386caa20>, get_entity_configs_callable=None), PythonCallableFunction(id='deleteUser', type='PythonCallableFunction', display_name='deleteUser', description='This can only be done by the logged in user.', sample_questions=[], confirm=True, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {'path_params': {'type': 'object', 'properties': {'username': {'type': 'string', 'description': 'The name that needs to be deleted'}}, 'required': ['username']}}, 'required': []}), is_fallback=False, execute_callable=<function OpenAPILibrary.openai_fns_to_openapi_function.<locals>.wrapped_fn at 0x1386ca160>, get_entity_configs_callable=None), IndexFunction(id='index', type='IndexFunction', display_name='List functions', description='List the functions available to the assistant. This is a list of things you can ask.', sample_questions=['What can you do?', 'What can I ask?', 'Which functions are defined?'], confirm=False, parameters=BaseFunctionParameters(json_schema={'type': 'object', 'properties': {}, 'required': []}), is_fallback=False, functions=<bound method Assistant.get_all_functions of <openassistants.core.assistant.Assistant object at 0x1386d8050>>)]]
```

and `user_query` is
```
What can I ask?
```

I see that the returned `results` variable is
```
['show_functions', {'$ref': '#/definitions/functions', 'value': 'find_email'}, 'findPetsByTags', 'getInventory', 'createUsersWithListInput', 'loginUser', 'index']
```

which throws an error
```bash
Traceback (most recent call last):
  File "/Users/user/Projects/definitive-io/openassistants/packages/openassistants-fastapi/openassistants_fastapi/utils/sse.py", line 25, in _patch_iter
    async for new in src:
  File "/Users/user/Projects/definitive-io/openassistants/packages/openassistants-fastapi/openassistants_fastapi/routes.py", line 37, in stream
    async for version in assistant.run_chat(
  File "/Users/user/Projects/definitive-io/openassistants/packages/openassistants/openassistants/core/assistant.py", line 404, in run_chat
    async for version in self.handle_user_plaintext(
  File "/Users/user/Projects/definitive-io/openassistants/packages/openassistants/openassistants/core/assistant.py", line 239, in handle_user_plaintext
    function_selection = await self.run_function_selection(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/definitive-io/openassistants/packages/openassistants/openassistants/core/assistant.py", line 211, in run_function_selection
    select_function_result = await select_function(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Projects/definitive-io/openassistants/packages/openassistants/openassistants/llm_function_calling/selection.py", line 78, in select_function
    function_names: set[str] = set(filter(None, results))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

Is this the limitation of the model? Or do I need to modify config for local models?

Thanks!

**Comment by abhinavkulkarni** [comment]
Hey @ricklamers,

I tried this with Mixtral 8x7B as well as OpenAI and it does work.
